stages:
  - check

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_NOLOGO: "true"

build:
  stage: check
  tags:
    - docker

  image: mcr.microsoft.com/dotnet/sdk:10.0

  script:
    - dotnet restore
    - dotnet build --no-restore --configuration Debug

lint:
  stage: check
  tags:
    - docker

  image: mcr.microsoft.com/dotnet/sdk:10.0

  script:
    - dotnet tool restore
    - dotnet format --verify-no-changes --verbosity normal
    - dotnet csharpier check .